name: '${project.name}'
version: '${project.version}'
main: '${project.groupId}.PortalRideThru'
api-version: '1.17'
#description: ''
author: YourMJK
website: https://github.com/YourMJK/PortalRideThru
